name: LXJS 2014
markdown: redcarpet
pygments: true

# We are adding this below:
source: ./src
destination: ./build

asset_pipeline:
  bundle: true
  compress: true
  output_path: assets
  display_path: assets
  gzip: false

speakers:
  - name: Feross Aboukhadijeh
    machine_name: feross_aboukhadijeh
    title: Mad scientist, PeerCDN
    twitter: feross
  - name: Tom Ashworth
    machine_name: tom_ashworth
    title: Front-end engineer, Twitter
    twitter: phuunet

sponsors:
  async:
    - name: Microsoft
      logo: logo-sponsor-microsoft.png
      url: http://www.microsoft.com/