name: LXJS 2014
markdown: redcarpet
pygments: true

# We are adding this below:
source: ./src
destination: ./build

asset_pipeline:
  bundle: true
  compress: true
  output_path: assets
  display_path: assets
  gzip: false