name: LXJS 2014
markdown: redcarpet
pygments: true

# We are adding this below:
source: ./src
destination: ./build

asset_pipeline:
  bundle: true
  compress: true
  output_path: assets
  display_path: assets
  gzip: false

speakers:
  - name: Addy Osmani
    machine_name: addy_osmani
    title: Senior Engineer In Developer Relations, Google
    twitter: addyosmani
  - name: Brittany Storoz
    machine_name: brittany_storoz
    title: Interactive Developer, New York Times
    twitter: brittanystoroz
  - name: Charlie Robbins
    machine_name: charlie_robbins
    title: Founder, CEO. Nodejitsu
    twitter: indexzero
  - name: Feross Aboukhadijeh
    machine_name: feross_aboukhadijeh
    title: Mad scientist, PeerCDN
    twitter: feross
  - name: Martin Boßlet
    machine_name: martin_bosslet
    title: Independent developer
    twitter: _emboss_
  - name: Mike Brevoort
    machine_name: mike_brevoort
    title: Chief Architect of Innovation and Advanced Development, Pearson HigherEd
    twitter: mbrevoort
  - name: Roger Wang
    machine_name: roger_wang
    title: Creator and maintainer, node-webkit project
    twitter: wwr
  - name: Tim Park
    machine_name: tim_park
    title: Open platforms and Internet of Things, Microsoft
    twitter: timpark
  - name: Tom Ashworth
    machine_name: tom_ashworth
    title: Front-end engineer, Twitter
    twitter: phuunet
  - name: Tracy Hinds
    machine_name: tracy_hinds
    title: PDXNode|CascadiaJS organizer, Web Engineer, Urban Airship
    twitter: HackyGoLucky
  - name: Wyatt Preul
    machine_name: wyatt_preul
    title: Software Architect
    twitter: wpreul

sponsors:
  async:
    - name: Blip
      logo: logo-sponsor-blip.png
      url: http://www.blip.pt/
    - name: Microsoft
      logo: logo-sponsor-microsoft.png
      url: http://www.microsoft.com/
  sync:
    - name: Digital Ocean
      logo: logo-sponsor-digitalocean.png
      url: https://www.digitalocean.com
    - name: Sauce Labs
      logo: logo-sponsor-saucelabs.png
      url: https://saucelabs.com/